# Generated by Django 5.2.5 on 2025-08-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
