# Generated by Django 5.2.5 on 2025-08-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_remove_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unit_price',
        ),
    ]
